### ISSUE TITLE
Wrong selection

### ISSUE THREAD

**Issue by YasinKalca** [CzechPMDevs/BuilderTools#218]
Lets say i do //replace 1:0 19 

it will replace every block that is like stone e.g 1:1,1:2,1:3 etc will be changed eventough i selected a specific block

**Comment by VixikHD** [comment]
Your issue is missing certain information required for fixing the bug. 

Without knowing your Plugin version, PocketMine-MP version, OS, PHP, Client version, other plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.

Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
